---
# file: tasks/install-node-exporter.yml
#
# Install Prometheus node-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#
- name: set internal variables for convenience
  set_fact:
    prometheus_node_exporter_subdir: "{{ prometheus_install_path }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_suffix }}"
    prometheus_node_exporter_tarball_path: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"


- name: set download url for versions >= 0.13.0
  set_fact:
    prometheus_node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
  when: prometheus_node_exporter_version | version_compare('0.13.0', '>=')

- name: set download url for versions < 0.13.0 (OBSOLETE!)
  set_fact:
    prometheus_node_exporter_tarball_url: "https://github.com/prometheus/node_exporter/releases/download/{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
  when: prometheus_node_exporter_version | version_compare('0.13.0', '<')

- name: set daemon dir for versions >= 0.12
  set_fact:
    prometheus_node_exporter_daemon_dir: "{{ prometheus_node_exporter_subdir }}"
  when: prometheus_node_exporter_version | version_compare('0.12', '>=')

- name: set daemon dir for versions < 0.12 (OBSOLETE!)
  set_fact:
    prometheus_node_exporter_daemon_dir: "{{ prometheus_install_path }}"
  when: prometheus_node_exporter_version | version_compare('0.12', '<')

- name: download node_exporter tarball
  get_url:
    url: "{{ prometheus_node_exporter_tarball_url }}"
    dest: "{{ prometheus_node_exporter_tarball_path }}"

- name: untar node_exporter tarball
  unarchive:
    src: "{{ prometheus_node_exporter_tarball_path }}"
    dest: "{{ prometheus_install_path }}"
    remote_src: yes
    copy: no

- name: set permissions, owner and group
  file: path={{ prometheus_node_exporter_daemon_dir }}/node_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"

- name: mkdir for data
  file:
    path: "{{ prometheus_db_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="

- name: set node_exporter variables
  copy: src="../files/etc-default-node_exporter"  dest=/etc/default/node_exporter
  register: node_exporter_config

- debug: var=node_exporter_config
  notify: reload node_exporter
  when: node_exporter_config.changed


- name: copy INIT script to server
  template: src="../templates/node_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/node_exporter"  mode="a+x"
  when: not prometheus_node_exporter_use_systemd|bool

- name: copy systemd config to server
  template: src="../templates/node_exporter.service.j2"  dest="/lib/systemd/system/node_exporter.service"
  when: prometheus_node_exporter_use_systemd|bool


- name: set INIT status and start
  service: name=node_exporter enabled=yes state=started
